### ISSUE TITLE
Is there any plan to add GPT-4 version?

### ISSUE THREAD

**Issue by fahimanwer** [kevinamiri/maila#1]
Hey, I saw a huge difference in GPT-3 and 4, So, is there any chance to get GPT-4 api Version along with 3.5

**Comment by kevinamiri** [comment]
Let me see this weekend. If I had the time, I will clean up the code and fix the backend api's as well. sure, I will. I'm going to add chatgpt/gpt-4 compatible APIs.

**Comment by fahimanwer** [comment]
Thanks for the update.
